name: CI ETL PYTHON
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}
      - name: do the pack
        run: aws cloudformation package --template-file cloudformation_template.yaml --s3-bucket lambdacretu --output-template-file cloudformation_template.packaged.yaml
      - name: do the stack
        run: aws cloudformation deploy --template-file cloudformation_template.packaged.yaml --stack-name CloudGuruChallange --capabilities CAPABILITY_IAM --parameter-overrides RdsUsername=${{ secrets.RDS_Username }} RdsPass=${{ secrets.RDS_PASS }}
