name: "Deploy SAM Stack to Production"
on:
  push:
    branches:
    - sam

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: falnyr/aws-sam-deploy-action@v1.2.1
      env:
        TEMPLATE: 'sam-template.yaml'
        AWS_STACK_NAME: my-serverless-application
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEPLOY_BUCKET: lambdacretu
